package brain

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/naglezhang/makro/internal/llm"
)

// Proposal is one suggestion the brain offers the user. Generated by the LLM
// from a ReadSnapshot, gated by confidence, and (if it passes) written to
// memory as category=proposals + pushed to the user.
type Proposal struct {
	Title      string  `json:"title"`      // one line, the hook
	Body       string  `json:"body"`       // what to do + why, a few sentences
	Confidence float64 `json:"confidence"` // 0.0–1.0, brain's guess I'll act
	Domain     string  `json:"domain"`     // e.g. "rust", "side-project", short tag
	Reason     string  `json:"reason"`     // why now, why this not something else
}

const defaultProposePrompt = `你是用户的「个人第二大脑」。用户记性差、主意多、懒——需要被派活才会动。

你的任务：基于下面提供的「用户最近的对话(capture)」「用户画像(profile)」「当前 open 的 proposal」「最近 accept/reject 反馈」，生成 ONE 个 proposal——建议用户接下来最该做的一件事。

判断标准（这就是 confidence 的含义）：
- 用户最近聊过、表现出兴趣，但还没动手的事 → 高 confidence
- 用户历史 accept 率高的领域 → 加权
- 用户连续 ignore 或 accept 了但从没真做完的领域 → 大幅降权
- 已经在 open proposal 里的同类事 → 不要重复推（降权或换角度）

输出要求：严格只输出一个 JSON 对象，不要任何额外文字、不要 markdown 代码块：
{"title":"一句话标题（动词开头）","body":"建议做什么 + 为什么，2-4 句","confidence":0.0到1.0的数字,"domain":"一个词的领域标签","reason":"为什么是现在推这个，而不是别的"}

如果信号不足（capture 太少、没有明显可推的事），confidence 给低分（<0.3）并让 body 说明"信号不足"。不要硬编造用户没提过的事。`

// Proposer turns a ReadSnapshot into a Proposal via a single LLM call. It
// mirrors internal/agent/guardian.go's SessionAssessor exactly: own timeout,
// system+user message pair, brace-scrape the JSON out of the response, parse.
// No tools, no streaming — one Complete() call.
type Proposer struct {
	provider llm.Provider
	model    string
	prompt   string
}

// NewProposer builds a proposer. prompt may be "" to use the default.
func NewProposer(provider llm.Provider, model, prompt string) *Proposer {
	if prompt == "" {
		prompt = defaultProposePrompt
	}
	return &Proposer{provider: provider, model: model, prompt: prompt}
}

// Propose generates one proposal from the snapshot. Returns the proposal and
// nil error on success. A low-quality response (unparseable JSON) returns an
// error — the caller treats that as "skip this wake, don't push garbage."
func (p *Proposer) Propose(ctx context.Context, snap ReadSnapshot) (*Proposal, error) {
	userMsg := buildProposeUserMessage(snap)

	// Own the timeout — don't depend on the caller's deadline. 60s is generous
	// because GLM can be slow; the brain is background so latency is fine, but
	// we must not hang forever.
	callCtx, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()

	msgs := []llm.Message{
		{Role: llm.RoleSystem, Content: p.prompt},
		{Role: llm.RoleUser, Content: userMsg},
	}
	opts := llm.GenerateOptions{Model: p.model, MaxTokens: 1024}

	start := time.Now()
	result, err := p.provider.Complete(callCtx, msgs, opts)
	if err != nil {
		return nil, fmt.Errorf("propose LLM call: %w", err)
	}
	log.Printf("[brain] propose LLM done in %s, content_len=%d", time.Since(start).Round(time.Millisecond), len(result.Content))

	raw := strings.TrimSpace(result.Content)
	scraped := braceScrape(raw)
	if scraped == "" {
		return nil, fmt.Errorf("propose: no JSON object in response (content len %d)", len(result.Content))
	}

	var prop Proposal
	if err := json.Unmarshal([]byte(scraped), &prop); err != nil {
		return nil, fmt.Errorf("propose: parse JSON: %w (raw: %s)", err, truncate(raw, 120))
	}
	if prop.Title == "" || prop.Body == "" {
		return nil, fmt.Errorf("propose: empty title/body in response")
	}
	// Clamp confidence to [0,1] — models occasionally emit 1.2 or -0.1.
	if prop.Confidence < 0 {
		prop.Confidence = 0
	} else if prop.Confidence > 1 {
		prop.Confidence = 1
	}
	return &prop, nil
}

// buildProposeUserMessage assembles the R1–R5 snapshot into a single user
// prompt for the LLM. Structured sections so the model can cite which signal
// drove its confidence. Trimmed to keep total under ~6k chars (LLM context
// budget; the fit signal matters more than exhaustive history).
func buildProposeUserMessage(snap ReadSnapshot) string {
	var b strings.Builder
	b.WriteString("以下是用户 memory 的近期快照（R1-R5）。基于这些生成一个 proposal。\n\n")

	writeSection(&b, "【R1 用户最近 7 天的对话 capture（idea 矿）】", summarizeMemories(snap.Captures, 3000))
	writeSection(&b, "【R2 用户画像（character/preferences/soul）】", summarizeMemories(snap.Profile, 1500))
	writeSection(&b, "【R3 当前 open 的 proposal（说了要做还没做）】", summarizeMemories(snap.OpenProps, 1000))
	writeSection(&b, "【R4 最近 30 天 accept/reject 反馈（拟合命脉）】", summarizeMemories(snap.Feedback, 2000))

	if len(snap.Recents) > 0 {
		titles := make([]string, 0, len(snap.Recents))
		for _, m := range snap.Recents {
			if t := firstLine(m.Content); t != "" {
				titles = append(titles, t)
			}
		}
		if len(titles) > 0 {
			fmt.Fprintf(&b, "【R5 最近已推过的 proposal 标题（不要重复）】\n%s\n\n", strings.Join(titles, "\n"))
		}
	}

	if len(snap.ReadErrors) > 0 {
		fmt.Fprintf(&b, "【注意】部分 memory 读取失败（已用已有数据继续）：%s\n", strings.Join(snap.ReadErrors, "; "))
	}
	return b.String()
}

func writeSection(b *strings.Builder, header, body string) {
	b.WriteString(header)
	b.WriteByte('\n')
	if body == "" {
		b.WriteString("（无）\n\n")
		return
	}
	b.WriteString(body)
	b.WriteString("\n\n")
}

// summarizeMemories flattens a memory slice into "content" lines, capped at
// maxChars total. Each line is the memory's content (truncated per-line too).
// Empty input → "".
func summarizeMemories(ms []ListedMemory, maxChars int) string {
	if len(ms) == 0 {
		return ""
	}
	var b strings.Builder
	for i, m := range ms {
		line := strings.TrimSpace(m.Content)
		if line == "" {
			continue
		}
		line = fmt.Sprintf("- %s", truncate(line, 200))
		b.WriteString(line)
		b.WriteByte('\n')
		if b.Len() >= maxChars {
			fmt.Fprintf(&b, "...（还有 %d 条省略）\n", len(ms)-i-1)
			break
		}
	}
	return strings.TrimRight(b.String(), "\n")
}

// braceScrape extracts the first {...} balanced JSON object from s. Models
// often wrap JSON in prose ("Here is the proposal: {...}") or markdown fences.
// Ported verbatim from guardian.go's brace-scrape logic.
func braceScrape(s string) string {
	start := strings.IndexByte(s, '{')
	if start < 0 {
		return ""
	}
	// Find the matching close brace by depth counting (handles nested objects).
	depth := 0
	for i := start; i < len(s); i++ {
		switch s[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return s[start : i+1]
			}
		}
	}
	// Unbalanced — fall back to first { to last }.
	end := strings.LastIndexByte(s, '}')
	if end > start {
		return s[start : end+1]
	}
	return ""
}
