// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(160796325);
}

/**
 * ListMonitors returns names of sessions being monitored.
 * @returns {$CancellablePromise<string[]>}
 */
export function ListMonitors() {
    return $Call.ByID(660487912).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * LoadChatHistory returns persisted chat messages for frontend to render.
 * @returns {$CancellablePromise<$models.HistoryMessage[]>}
 */
export function LoadChatHistory() {
    return $Call.ByID(1452062887).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} input
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(input) {
    return $Call.ByID(1063940756, input);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(893176384, app);
}

/**
 * StartMonitor watches a session: waits for idle, auto-handles confirmations.
 * @param {string} sessionName
 * @returns {$CancellablePromise<void>}
 */
export function StartMonitor(sessionName) {
    return $Call.ByID(1535227845, sessionName);
}

/**
 * @param {application$0.Context} ctx
 * @returns {$CancellablePromise<void>}
 */
export function Startup(ctx) {
    return $Call.ByID(2837437396, ctx);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.HistoryMessage.createFrom;
const $$createType2 = $Create.Array($$createType1);
