// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * @param {string} sessionName
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function AttachSession(sessionName, cols, rows) {
    return $Call.ByID(592160856, sessionName, cols, rows);
}

/**
 * @param {string} sessionName
 * @returns {$CancellablePromise<void>}
 */
export function DetachSession(sessionName) {
    return $Call.ByID(779523470, sessionName);
}

/**
 * @param {string} sessionName
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminal(sessionName, cols, rows) {
    return $Call.ByID(3061528445, sessionName, cols, rows);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(2047978558, app);
}

/**
 * @param {application$0.Context} ctx
 * @returns {$CancellablePromise<void>}
 */
export function Startup(ctx) {
    return $Call.ByID(2998035714, ctx);
}

/**
 * @param {string} sessionName
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteInput(sessionName, data) {
    return $Call.ByID(4291681096, sessionName, data);
}
