// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CapturePane returns the current visible content of a tmux session's pane.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function CapturePane(name) {
    return $Call.ByID(3708230577, name);
}

/**
 * @param {string} name
 * @param {string} workingDir
 * @returns {$CancellablePromise<void>}
 */
export function CreateSession(name, workingDir) {
    return $Call.ByID(3349502537, name, workingDir);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function KillSession(name) {
    return $Call.ByID(3242586865, name);
}

/**
 * @returns {$CancellablePromise<$models.Session[]>}
 */
export function ListSessions() {
    return $Call.ByID(4149145774).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Session.createFrom;
const $$createType1 = $Create.Array($$createType0);
