import Foundation

struct Session: Codable, Identifiable, Equatable {
    let name: String
    let active: Bool
    var working: Bool
    var unread: Int
    var id: String { name }

    init(name: String, active: Bool, working: Bool = false, unread: Int = 0) {
        self.name = name
        self.active = active
        self.working = working
        self.unread = unread
    }

    private enum CodingKeys: String, CodingKey { case name, active, working, unread }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        name = try c.decode(String.self, forKey: .name)
        active = try c.decode(Bool.self, forKey: .active)
        // working/unread are omitempty on the server → decodeIfPresent for
        // backward compatibility with payloads that omit them.
        working = try c.decodeIfPresent(Bool.self, forKey: .working) ?? false
        unread = try c.decodeIfPresent(Int.self, forKey: .unread) ?? 0
    }
}

// Posted by ChatViewModel when a session_state WS event arrives, so the
// Sessions list can update working/unread in real time without polling.
extension Notification.Name {
    static let sessionStateChanged = Notification.Name("makro.sessionStateChanged")
}

struct KanbanTask: Codable, Identifiable, Equatable {
    let id: String
    let title: String
    let content: String
    let column: String
    let order: Int
    let createdAt: String?
    let updatedAt: String?
    let assignedSession: String?

    enum CodingKeys: String, CodingKey {
        case id, title, content, column, order
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case assignedSession = "assigned_session"
    }
}

struct ChatMessage: Identifiable, Equatable {
    enum Role: String, Codable {
        case user, assistant, system
    }

    let id: UUID
    let role: Role
    var text: String
    let timestamp: Date

    init(id: UUID = UUID(), role: Role, text: String, timestamp: Date = Date()) {
        self.id = id
        self.role = role
        self.text = text
        self.timestamp = timestamp
    }
}

// A plan the assistant proposed during a voice call, awaiting the user's
// confirmation before it is dispatched to a coding-agent session. Received via
// the `plan` WS event; confirmed/denied via /api/chat/confirm|deny.
struct PendingPlan: Codable, Equatable {
    let session: String   // 执行者 (target session)
    let summary: String   // 一句话做什么
    let brief: String     // 给该 session 的具体指令
}

// Voice-call interaction mode. Picked from a dropdown at the top of CallView;
// sent to the backend on call start / switch. The backend applies per-mode
// behavior (prefix + tool gate + plan staging). Default = .plan (落实).
enum CallMode: String, CaseIterable, Codable {
    case chat, plan, query

    var label: String {
        switch self {
        case .chat: return "闲聊"
        case .plan: return "落实"
        case .query: return "查询"
        }
    }

    /// One-line hint shown under the mode name in the picker.
    var hint: String {
        switch self {
        case .chat: return "纯对话，说完就答"
        case .plan: return "讨论→提议→确认→派发"
        case .query: return "查 session/项目状态，不派发"
        }
    }
}

enum ConnectionState: Equatable {
    case disconnected
    case connecting
    case connected
}

// A discoverable artifact (HTML page or video) generated by an AI agent,
// surfaced from the agent's session working directory.
struct Artifact: Codable, Identifiable, Equatable {
    let session: String // owning tmux session (central-store tag)
    let name: String    // basename
    let path: String    // relative to session cwd
    let type: String    // "html" or "video"
    let mtime: Int64    // unix seconds
    let size: Int64     // bytes

    // Cross-session uniqueness: two sessions can both have "report.html".
    var id: String { "\(session)/\(path)" }
    var isHTML: Bool { type == "html" }
    var isVideo: Bool { type == "video" }
}
